[package]
name = "papertrain"
version = "0.1.0"
authors = ["Dirk Van Haerenborgh <vhdirk@gmail.com>"]
homepage = "https://github.com/vhdirk/papertrain"
edition = "2021"
resolver = "2"
rust-version = "1.73"

[profile.release]
opt-level = "s"
lto = "off"

[profile.dev]
debug = true    # Symbols are nice and they don't increase the size on Flash
opt-level = "z"
lto = "off"

[profile.dev.package.esp-wifi]
opt-level = 3

# # [features]
# # default = ["alloc", "esp-idf-sys/native", "experimental"]
# # std = ["alloc", "esp-idf-sys/std", "esp-idf-sys/binstart", "embedded-svc/std", "esp-idf-hal/std", "esp-idf-svc/std"]
# # alloc = ["embedded-svc/alloc", "esp-idf-hal/alloc", "esp-idf-svc/alloc"]
# # experimental = ["embedded-svc/experimental", "esp-idf-svc/experimental"]

# # [dependencies]
# # anyhow = "^1.0.75"
# # log = { version = "^0.4" }
# # esp-idf-sys = { version = "^0.33" }
# # esp-idf-hal = { version = "^0.42" }
# # esp-idf-svc = { version = "^0.47" }
# # embedded-svc = { version = "^0.26" }

# # epd-waveshare = { git = "https://github.com/caemor/epd-waveshare", rev = "cff9130" }

# # querystring = "1.1.0"
# # # serde_json = "1.0.107"
# # serde = { version = "1.0.189",  default-features = false, features = ["derive", "alloc"]}
# # serde-json-core = "0.5.1"

# [features]
# default = []
# # pio = ["esp-idf-svc/pio"]
# # std = ["alloc", "esp-idf-svc/binstart", "esp-idf-svc/std"]
# # alloc = ["esp-idf-svc/alloc"]
# # nightly = ["esp-idf-svc/nightly"]
# # experimental = ["esp-idf-svc/experimental"]
# # embassy = ["esp-idf-svc/embassy-sync", "esp-idf-svc/critical-section", "esp-idf-svc/embassy-time-driver"]

[dependencies]
# # anyhow = "^1.0.75"

defmt = "^0.3.5"

hal = { package = "esp32s3-hal", version="0.12.0", features = [
    "rt",
    "async",
    "defmt",
    "embassy",
    "embassy-executor-thread",
    "embassy-time-systick",
] }

embedded-hal = "0.2.7"

esp-backtrace = { version = "0.8.0", default-features = false, features = [
    "esp32s3",
    "panic-handler",
    "exception-handler",
    "print-uart",
] }
esp-println = { git = "https://github.com/esp-rs/esp-println", default-features = false, features = [
    "esp32s3",
    "defmt",
    "uart",
] }
esp-alloc = "0.3.0"

# # defmt-rtt = "0.4"
embassy-executor = { version = "0.3.0", features = [
    "nightly",
    "defmt",
    "executor-thread",
] }
embassy-time = { version = "0.1.5", features = ["nightly", "defmt"] }
embassy-net = { version = "0.1.0", features = [
    "defmt",
    "tcp",
    "udp",
    "dns",
    "dhcpv4",
    "medium-ethernet",
    "unstable-traits",
    "nightly"
] }
esp-wifi = { git = "https://github.com/esp-rs/esp-wifi", rev = "d38763f", default-features = false, features = [
    "esp32s3",
    "utils",
    "wifi",
    "embedded-svc",
    "embassy-net",
    "defmt",
    "async"
] }

embedded-io  = { package = "embedded-io-async", version = "0.5.0", optional = true }
# tokio = { version = "1.21.2", features = ["full"] }
reqwless = { version = "0.6.0", features = ["alloc", "defmt"] }
# heapless = { version = "0.7.14", default-features = false }
# # esp-idf-sys = { version = "^0.33" }
# # esp-idf-hal = { version = "^0.42" }
# # esp-idf-svc = { version = "0.47.1", default-features = false }
embedded-svc = { version = "^0.25", default-features = false, features = ["nightly", "defmt" ] }
epd-waveshare = { git = "https://github.com/caemor/epd-waveshare", rev = "cff9130" }

# # querystring = "1.1.0"
# # serde_json = "1.0.107"
# # serde = { version = "1.0.189",  default-features = false, features = ["derive", "alloc"]}
# serde-json-core = "0.5.1"

# [patch.'https://github.com/esp-rs/esp-wifi.git']
# esp-wifi = { path = "../esp-wifi/esp-wifi" }

# [patch.'https://github.com/esp-rs/esp-hal.git']
# esp32c6-hal = { git = "https://github.com/esp-rs/esp-hal.git", rev = "29f3518" }
# esp-hal-common = {  git = "https://github.com/esp-rs/esp-hal.git", rev = "29f3518", version = "^0.15.0"}

# [patch.crates-io]
# esp32c6-hal = { git = "https://github.com/esp-rs/esp-hal.git", rev = "29f3518" }
# esp-hal-common = {  git = "https://github.com/esp-rs/esp-hal.git", rev = "29f3518" }

[build-dependencies]
anyhow = "^1.0.75"
# embuild = "^0.31.3"
