[package]
name = "papertrain"
version = "0.1.0"
authors = ["Dirk Van Haerenborgh <vhdirk@gmail.com>"]
homepage = "https://github.com/vhdirk/papertrain"
edition = "2021"
resolver = "2"
rust-version = "1.73"

[profile.release]
opt-level = "s"
lto = "off"

[profile.dev]
debug = true    # Symbols are nice and they don't increase the size on Flash
opt-level = "z"
lto = "off"

[profile.dev.package.esp-wifi]
opt-level = 3


[dependencies]
# # anyhow = "^1.0.75"

defmt = "^0.3.5"

esp-hal = { package = "esp32s3-hal", version="0.13.0", features = [
    "rt",
    "async",
    "defmt",
    "embassy",
    "embassy-executor-thread",
    "embassy-time-systick",
] }

embedded-hal = "0.2.7"

esp-backtrace = { version = "0.9.0", default-features = false, features = [
    "esp32s3",
    "panic-handler",
    "exception-handler",
    "print-uart",
] }
esp-println = { git = "https://github.com/esp-rs/esp-println", default-features = false, features = [
    "esp32s3",
    "defmt",
    "uart",
] }
esp-alloc = "0.3.0"

# # defmt-rtt = "0.4"
embassy-executor = { version = "0.3.1", features = [
    "nightly",
    "defmt",
    "executor-thread",
] }
embassy-time = { version = "0.1.5", features = ["nightly", "defmt"] }
embassy-net = { version = "0.2.1", features = [
    "defmt",
    "tcp",
    "udp",
    "dns",
    "dhcpv4",
    "proto-ipv4",
    "proto-ipv6",
    "nightly",
] }
esp-wifi = { git = "https://github.com/vhdirk/esp-wifi", default-features = false, features = [
    "esp32s3",
    "utils",
    "wifi",
    "embedded-svc",
    "embassy-net",
    "defmt",
    "async"
] }

embedded-io  = { package = "embedded-io-async", version = "0.6.0" }
embedded-nal = { package = "embedded-nal-async", version = "0.6.0" }
reqwless = { version = "0.9.0", features = ["alloc", "defmt", "embedded-tls"] }

embedded-svc = { version = "^0.26.1", default-features = false, features = ["nightly", "defmt" ] }
epd-waveshare = { git = "https://github.com/caemor/epd-waveshare", rev = "cff9130" }
toml-cfg = "0.1.3"

# # querystring = "1.1.0"
# # serde_json = "1.0.107"
serde = { version = "1.0.189",  default-features = false, features = ["derive", "alloc"]}
serde-json-core = "0.5.1"
anyhow = {version = "^1.0.75", default-features = false }
heapless = { version = "0.7.16", default-features = false }
embassy-futures = { version = "0.1.0", features = ["defmt"] }
static_cell = { version = "2.0.0", features = ["nightly"] }

[patch.crates-io]
reqwless = {git = "https://github.com/vhdirk/reqwless", branch = "old"}
buffered-io = { git = "https://github.com/bugadani/buffered-io.git", branch = "old", version = "0.4.2" }

[build-dependencies]
anyhow = "^1.0.75"
