[build]
target = "xtensa-esp32s3-none-elf"

[target.xtensa-esp32s3-none-elf]
# linker = "ldproxy"
runner = "espflash flash --baud=1048576 --monitor" # Select this runner for espflash v2.x.x
rustflags = [
    "-C", "link-arg=-nostartfiles",
    "-C", "link-arg=-Wl,-Tlinkall.x",
    "-C", "link-arg=-Trom_functions.x",
    "-C", "link-arg=-Tdefmt.x",
    # "-C", "force-frame-pointers",
]

[unstable]
build-std = ["core", "alloc", "panic_abort"]

[env]
MCU = "esp32s3"

DEFMT_LOG = "INFO"
ESP_LOGLEVEL = "INFO"
SMOLTCP_DNS_MAX_SERVER_COUNT = "10"
