#![no_std]
#![no_main]
#![feature(type_alias_impl_trait)]
#![feature(async_fn_in_trait)]

#[macro_use]
extern crate alloc;

use alloc::{boxed::Box, string::ToString, vec::Vec};

use irail::{Connection, Connections};
use wifi::WifiConfig;

use defmt::*;
use embassy_executor::Spawner;
use embassy_net::{
    dns::DnsSocket,
    tcp::client::{TcpClient, TcpClientState},
    Config, Stack, StackResources,
};

use epd_waveshare;
use esp_println::{self as _, println};
use reqwless::client::{HttpClient, TlsConfig, TlsVerify};

use core::mem::MaybeUninit;
use core::option::Option::*;

use embassy_time::{Duration, Timer};
use embedded_hal_bus::spi::ExclusiveDevice;

use esp_hal::{
    clock::ClockControl,
    dma::DmaPriority,
    embassy::{self},
    entry,
    gdma::Gdma,
    gpio::IO,
    peripherals::Peripherals,
    prelude::*,
    spi::{
        master::{prelude::*, Spi},
        SpiMode,
    },
    systimer::SystemTimer,
    timer::TimerGroup,
    FlashSafeDma, Rng,
};

use embedded_graphics::{
    mono_font::{
        ascii::{FONT_6X10, FONT_8X13, FONT_9X18_BOLD},
        MonoTextStyle,
    },
    prelude::*,
    primitives::{Line, PrimitiveStyle, Rectangle},
    text::{renderer::CharacterStyle, Alignment, DecorationColor, Text, TextStyle},
};

use epd_waveshare::{
    epd7in5b_v3::{Display7in5, Epd7in5, HEIGHT, WIDTH},
    prelude::*,
};

use esp_wifi::{
    initialize,
    wifi::{WifiController, WifiDevice, WifiStaDevice},
    EspWifiInitFor,
};
use static_cell::make_static;

use crate::irail::IRailClient;

mod config;
mod irail;
mod stack_protection;
mod wifi;

#[global_allocator]
static ALLOCATOR: esp_alloc::EspHeap = esp_alloc::EspHeap::empty();

fn init_heap() {
    const HEAP_SIZE: usize = 130 * 1024;
    static mut HEAP: MaybeUninit<[u8; HEAP_SIZE]> = MaybeUninit::uninit();

    unsafe {
        ALLOCATOR.init(HEAP.as_mut_ptr() as *mut u8, HEAP_SIZE);
    }
}
const NUM_SPIDMA_DESCRIPTORS: usize =
    (((epd_waveshare::buffer_len(WIDTH as usize, HEIGHT as usize) + 4091) / 4092) + 1) * 3;

// Include config generated by build script
include!(concat!(env!("OUT_DIR"), "/user_config.rs"));

#[embassy_executor::task]
async fn connection(mut controller: WifiController<'static>, config: &'static WifiConfig) {
    info!("start connection task");
    // info!("Device capabilities: {:?}", controller.get_capabilities());
    loop {
        let _ = wifi::connection(&mut controller, config).await;
    }
}

#[embassy_executor::task]
async fn net_task(stack: &'static Stack<WifiDevice<'static, WifiStaDevice>>) {
    // select(stack.run(), async {
    //     // HACK: force polling the interface in case some write operation doesn't wake it up
    //     loop {
    //         Timer::after(Duration::from_secs(1)).await;
    //     }
    // })
    // .await;
    stack.run().await
}
fn display_header<Display>(
    display: &mut Display,
    connections: &Connections,
    // issues: &Vec<Issue>,
) -> Result<(), Display::Error>
where
    Display: DrawTarget<Color = TriColor>,
{
    let date = connections.timestamp.format("%d/%m/%Y").to_string();
    let time = connections.timestamp.format("%H:%M").to_string();

    let title_character_style = MonoTextStyle::new(&FONT_8X13, TriColor::Black);

    Text::with_text_style(
        &date,
        Point::new(13, 20),
        title_character_style,
        TextStyle::with_alignment(Alignment::Left),
    )
    .draw(display)?;

    Text::with_text_style(
        &time,
        Point::new(WIDTH as i32 / 2, 20),
        title_character_style,
        TextStyle::with_alignment(Alignment::Center),
    )
    .draw(display)?;

    // Draw separator line
    let line_vertical_position = 30;
    let separator_style = PrimitiveStyle::with_stroke(TriColor::Black, 1);
    Line::new(
        Point::new(0, line_vertical_position),
        Point::new(WIDTH as i32, line_vertical_position),
    )
    .into_styled(separator_style)
    .draw(display)?;

    Ok(())
}

fn display_connection<Display>(
    display: &mut Display,
    connection: &Connection,
    index: usize,
    offset: Point,
) -> Result<(), Display::Error>
where
    Display: DrawTarget<Color = TriColor>,
{
    let container_width: i32 = WIDTH as i32 / 3 - 20;
    let container_height: i32 = 150;
    let thin_stroke = PrimitiveStyle::with_stroke(TriColor::Black, 1);

    Rectangle::new(
        offset.clone(),
        Size::new(container_width as u32, container_height as u32),
    )
    .into_styled(thin_stroke)
    .draw(display)?;

    let departure_time = connection
        .departure
        .time
        .as_ref()
        .map_or("".to_string(), |t| t.format("%H:%M").to_string());
    let arrival_time = connection
        .arrival
        .time
        .as_ref()
        .map_or("".to_string(), |t| t.format("%H:%M").to_string());

    let mut departure_style = MonoTextStyle::new(&FONT_9X18_BOLD, TriColor::Black);

    let mut arrival_style = MonoTextStyle::new(&FONT_9X18_BOLD, TriColor::Black);

    let left_align = TextStyle::with_alignment(Alignment::Left);

    let right_align = TextStyle::with_alignment(Alignment::Right);

    let delay_style = MonoTextStyle::new(&FONT_9X18_BOLD, TriColor::Chromatic);

    let decoration_color = DecorationColor::Custom(TriColor::Chromatic);

    if connection.departure.canceled {
        departure_style.set_strikethrough_color(decoration_color);
    }

    Text::with_text_style(
        &departure_time,
        Point::new(offset.x + 20, offset.y + 30),
        departure_style,
        left_align,
    )
    .draw(display)?;

    if let Some(delay) = connection.departure.delay.as_ref() {
        if delay.num_minutes() > 0 {
            Text::with_text_style(
                &format!("+ {}'", &delay.num_minutes()),
                Point::new(offset.x + container_width - 20, offset.y + 100),
                delay_style,
                right_align,
            )
            .draw(display)?;
        }
    }

    if connection.arrival.canceled {
        arrival_style.set_strikethrough_color(decoration_color);
    }

    Text::with_text_style(
        &arrival_time,
        Point::new(offset.x + 20, offset.y + 100),
        arrival_style,
        left_align,
    )
    .draw(display)?;

    if let Some(delay) = connection.arrival.delay.as_ref() {
        if delay.num_minutes() > 0 {
            Text::with_text_style(
                &format!("+ {}'", &delay.num_minutes()),
                Point::new(offset.x + container_width - 20, offset.y + 100),
                delay_style,
                right_align,
            )
            .draw(display)?;
        }
    }

    // let connection_text = format!(
    //     "Train {}: {} - {} ({})",
    //     index + 1,
    //     connection.arrival.time.map_or("".to_string(), |t| t.format("%H:%M").to_string()),
    //     connection.departure.delay.unwrap()
    // );

    // let s = MonoTextStyle::new(&FONT_9X18_BOLD, TriColor::Black);
    // let connection_style = TextStyle::default();
    // Text::with_text_style(
    //     &connection_text,
    //     Point::new(offset.x + 20, offset.y + 30),
    //     s,
    //     connection_style,
    // )
    // .draw(display)?;

    Ok(())
}

fn display_connections<Display>(
    display: &mut Display,
    connections: &Vec<Connection>,
    vertical_offset: i32,
) -> Result<(), Display::Error>
where
    Display: DrawTarget<Color = TriColor>,
{
    if connections.len() == 0 {
        return Ok(());
    }

    let departure_station = connections[0]
        .departure
        .station_info
        .as_ref()
        .map_or("", |info| &info.name);
    let arrival_station = connections[0]
        .arrival
        .station_info
        .as_ref()
        .map_or("", |info| &info.name);

    let title = format!("{} -> {}", departure_station, arrival_station);

    let title_character_style = MonoTextStyle::new(&FONT_9X18_BOLD, TriColor::Black);
    let title_text_style = TextStyle::default();

    Text::with_text_style(
        &title,
        Point::new(20, vertical_offset),
        title_character_style,
        title_text_style,
    )
    .draw(display)?;

    // Text::with_text_style(&title, Point::new(x, y))
    //     .into_styled(text_style!(
    //         font = Font12x16,
    //         text_color = Black,
    //         background_color = White
    // ));

    // Draw train connections
    let mut y_position = vertical_offset + 15;
    let mut x_position = 10;
    for (index, connection) in connections.iter().enumerate() {
        display_connection(
            display,
            connection,
            index,
            Point::new(x_position, y_position),
        );
        x_position += WIDTH as i32 / 3; // Adjust spacing for the next connection
    }

    Ok(())
}

#[main]
async fn main(spawner: Spawner) -> ! {
    init_heap();

    info!("Logger is setup");

    let peripherals = Peripherals::take();

    let mut system = peripherals.SYSTEM.split();
    let clocks = ClockControl::max(system.clock_control).freeze();

    let timer = TimerGroup::new(peripherals.TIMG1, &clocks).timer0;

    let mut rng = Rng::new(peripherals.RNG);
    let stack_seed = rng.random();
    let tls_seed = rng.random();

    info!("Initializing wifi");

    let init = initialize(
        EspWifiInitFor::Wifi,
        timer,
        rng,
        system.radio_clock_control,
        &clocks,
    )
    .unwrap();

    let wifi = peripherals.WIFI;
    let (wifi_interface, controller) =
        esp_wifi::wifi::new_with_mode(&init, wifi, WifiStaDevice).unwrap();

    info!("Initializing embassy");

    embassy::init(&clocks, SystemTimer::new(peripherals.SYSTIMER));

    info!("Initializing dma interrupts");

    let io = IO::new(peripherals.GPIO, peripherals.IO_MUX);
    // let ledpin = gpio.gpio2;
    // let wakeup_pin = gpio.gpio4;

    let sclk = io.pins.gpio12.into_push_pull_output();
    let mosi = io.pins.gpio11.into_push_pull_output();
    let cs = io.pins.gpio10.into_push_pull_output();

    let busy = io.pins.gpio18.into_pull_up_input();
    let rst = io.pins.gpio16.into_push_pull_output();
    let dc = io.pins.gpio17.into_push_pull_output();

    esp_hal::interrupt::enable(
        esp_hal::peripherals::Interrupt::DMA_IN_CH0,
        esp_hal::interrupt::Priority::Priority1,
    )
    .unwrap();
    esp_hal::interrupt::enable(
        esp_hal::peripherals::Interrupt::DMA_OUT_CH0,
        esp_hal::interrupt::Priority::Priority1,
    )
    .unwrap();

    info!("Initializing spi with dma");
    let mut tx_descriptors = [0u32; NUM_SPIDMA_DESCRIPTORS];
    let mut rx_descriptors = [0u32; NUM_SPIDMA_DESCRIPTORS];
    let dma = Gdma::new(peripherals.DMA);
    let spi = Spi::new(peripherals.SPI2, 2u32.MHz(), SpiMode::Mode0, &clocks)
        .with_sck(sclk)
        .with_mosi(mosi)
        .with_dma(dma.channel0.configure(
            false,
            &mut tx_descriptors,
            &mut rx_descriptors,
            DmaPriority::Priority0,
        ));
    let mut spi_device =
        ExclusiveDevice::new(FlashSafeDma::<_, 4>::new(spi), cs, embassy_time::Delay {});

    let mut epd_driver = Epd7in5::new(&mut spi_device, busy, dc, rst, None)
        .await
        .unwrap();


    info!("Initializing network stack");
    let net_config = Config::dhcpv4(Default::default());

    // Init network stack
    let stack = &*make_static!(Stack::new(
        wifi_interface,
        net_config,
        make_static!(StackResources::<3>::new()),
        stack_seed.into()
    ));

    info!("Spawning Connection");
    spawner.spawn(connection(controller, &CONFIG.wifi)).ok();
    info!("Spawning Net Task");
    spawner.spawn(net_task(&stack)).ok();
    info!("Spawning Task");

    info!("Setting up wifi");
    loop {
        // wifi::connection(&mut controller, &CONFIG.wifi).await;
        if stack.is_link_up() {
            break;
        }
        Timer::after(Duration::from_millis(500)).await;
    }

    info!("Waiting to get IP address...");
    loop {
        if let Some(config) = stack.config_v4() {
            info!("Got IP: {}", config.address);
            break;
        }
        Timer::after(Duration::from_millis(500)).await;
    }

    info!("Creating http client");

    let mut tls_read_buf = [0; 16640];
    let mut tls_write_buf = [0; 16640];

    let client_state = TcpClientState::<1, 1024, 1024>::new();
    let tcp_client = TcpClient::new(&stack, &client_state);

    let dns = DnsSocket::new(&stack);
    let tls_config = TlsConfig::new(
    tls_seed.into(),
    &mut tls_read_buf,
    &mut tls_write_buf,
    TlsVerify::None,
    );

    let http_client = HttpClient::new_with_tls(&tcp_client, &dns, tls_config);

    info!("Fetching connections");

    let mut irail_client = IRailClient::new(&CONFIG.irail, http_client);

    loop {
        let connections = irail_client
            .get_connections(&CONFIG.connections[0].from, &CONFIG.connections[0].to)
            .await;

        let connections = if let Ok(connections) = connections {
            info!("Got connections: {}", connections);
            connections
        } else {
            let err = connections.unwrap_err();
            warn!("connections error");
            continue;
        };

        epd_driver.wake_up(&mut spi_device).await;
        // let connections: Connections = serde_json::from_str::<Connections>(RESPONSE).unwrap();
        println!("Draw!");

        let mut display = Box::new(Display7in5::default());

        println!("Clear the display");
        display.clear(TriColor::White).ok();


        display_header(display.as_mut(), &connections);
        let vertical_offset = 60;
        display_connections(display.as_mut(), &connections.connections, vertical_offset);

        // Transfer the frame data to the epd and display it
        epd_driver
            .update_and_display_frame(&mut spi_device, &display.buffer())
            .await
            .unwrap();

        println!("wait for idle!");
        // epd_driver.wait_until_idle(&mut spi_device).await;

        epd_driver.sleep(&mut spi_device).await;

        Timer::after(Duration::from_millis(15000)).await;
    }
}

//     //     let (_led_pin, wakeup_pin, modem, spi_driver, epd, delay) = gather_peripherals(peripherals)?;

//     //     let sysloop = EspSystemEventLoop::take()?;
//     //     let nvs = EspDefaultNvsPartition::take()?;

//     //     // see comment on function
//     //     //disable_onboard_led(led_pin)?;

//     //     // start wifi
//     //     // TODO: display error icon on screen and sleep again
//     //     let wifi = wifi::wifi(&CONFIG.wifi, modem, sysloop, nvs).expect("failed to connect to wifi");

//     //     // get image
//     //     log::info!("request image from server");
//     //     let mut client = IRailClient::new(CONFIG.irail.clone())?;

//     //     let connections = CONFIG
//     //         .connections
//     //         .map(|conn| client.get_connections(conn.from, conn.to));

//     //     log::info!("Got connection {:?}", connections[0].as_ref().unwrap());

//     //     // TODO: generate image from connections

//     //     // turn off wifi
//     //     log::info!("turning off wifi");
//     //     drop(wifi);

//     //     // TODO: draw the image

//     //     // if let Ok(image_data) = image_result {
//     //     //     log::info!("render image");
//     //     //     draw_epd(image_data, spi_driver, epd, delay)?;
//     //     // } else {
//     //     //     log::error!("getting image data failed: {:?}", image_result.unwrap_err());
//     //     // }

//     //     // deep sleep for 2 minutes (or on wakeup button press)
//     //     // TODO: sleep time should depend on train hours. The closer to departure, the more refreshes
//     //     enter_deep_sleep(wakeup_pin.into(), Duration::from_secs(60 * 2));

//     //     unreachable!("in sleep");
//}

// fn create_epd_driver(
//     spi_p: spi::SPI3,
//     sclk: AnyOutputPin,
//     sdo: AnyOutputPin,
//     _cs: AnyOutputPin,
//     busy_in: AnyInputPin,
//     rst: AnyOutputPin,
//     dc: AnyOutputPin,
// ) -> anyhow::Result<(SpiDev, EpdDriver, Delay)> {
//     let mut driver = spi::SpiDeviceDriver::new_single(
//         spi_p,
//         sclk,
//         sdo,
//         Option::<gpio::AnyIOPin>::None,
//         Option::<gpio::AnyOutputPin>::None,
//         &spi::config::DriverConfig::new(),
//         &spi::config::Config::new().baudrate(10.MHz().into()),
//     )?;

//     info!("driver setup completed");
//     let mut delay = Delay::new_default();

//     // Setup EPD
//     let epd_driver = Epd7in5::new(
//         &mut driver,
//         PinDriver::input(busy_in)?,
//         PinDriver::output(dc)?,
//         PinDriver::output(rst)?,
//         &mut delay,
//         None,
//     )
//     .unwrap();

//     info!("epd setup completed");

//     Ok((driver, epd_driver, delay))
// }

// // fn draw_epd(
// //     mut buffer: Vec<u8>,
// //     mut driver: SpiDev,
// //     mut epd: EpdDriver,
// //     mut delay: Delay,
// // ) -> anyhow::Result<()> {
// //     let expected_len = get_buffer_size();

// //     // check that what we got from the server is actually the same size as when me make a
// //     // epd_waveshare buffer of size WIDTH*HEIGHT pixels
// //     let buffer_len = buffer.len();
// //     if buffer_len != expected_len {
// //         anyhow::bail!("buffer len expected {}, got {}", expected_len, buffer_len);
// //     }
// //     let display = VarDisplay::<TriColor>::new(WIDTH, HEIGHT, &mut buffer, false)
// //         .expect("failed to create display");

// //     epd.update_and_display_frame(&mut driver, display.buffer(), &mut delay)
// //         .expect("display frame");
// //     info!("called display frame");
// //     delay.delay_ms(20_000u32);

// //     info!("done waiting, putting display to sleep");
// //     epd.sleep(&mut driver, &mut delay).expect("failed to sleep");

// //     Ok(())
// // }

pub const RESPONSE: &str = r#"
{
  "version": "1.2",
  "timestamp": "1698076701",
  "connection": [
    {
      "id": "0",
      "departure": {
        "delay": "60",
        "station": "Antwerp-South",
        "stationinfo": {
          "locationX": "4.390259",
          "locationY": "51.197828",
          "id": "BE.NMBS.008821196",
          "name": "Antwerp-South",
          "@id": "http://irail.be/stations/NMBS/008821196",
          "standardname": "Antwerpen-Zuid"
        },
        "time": "1698076860",
        "vehicle": "BE.NMBS.IC3017",
        "vehicleinfo": {
          "name": "BE.NMBS.IC3017",
          "shortname": "IC3017",
          "number": "3017",
          "type": "IC",
          "locationX": "0",
          "locationY": "0",
          "@id": "http://irail.be/vehicle/IC3017"
        },
        "platform": "3",
        "platforminfo": { "name": "3", "normal": "1" },
        "canceled": "1",
        "stops": {
          "number": "2",
          "stop": [
            {
              "id": "0",
              "station": "Sint-Niklaas",
              "stationinfo": {
                "locationX": "4.142966",
                "locationY": "51.171472",
                "id": "BE.NMBS.008894508",
                "name": "Sint-Niklaas",
                "@id": "http://irail.be/stations/NMBS/008894508",
                "standardname": "Sint-Niklaas"
              },
              "scheduledArrivalTime": "1698077700",
              "arrivalCanceled": "0",
              "arrived": "0",
              "scheduledDepartureTime": "1698077820",
              "arrivalDelay": "0",
              "departureDelay": "0",
              "departureCanceled": "0",
              "left": "0",
              "isExtraStop": "0",
              "platform": "?",
              "platforminfo": { "name": "?", "normal": "1" }
            },
            {
              "id": "1",
              "station": "Lokeren",
              "stationinfo": {
                "locationX": "3.987794",
                "locationY": "51.108062",
                "id": "BE.NMBS.008894201",
                "name": "Lokeren",
                "@id": "http://irail.be/stations/NMBS/008894201",
                "standardname": "Lokeren"
              },
              "scheduledArrivalTime": "1698078360",
              "arrivalCanceled": "0",
              "arrived": "0",
              "scheduledDepartureTime": "1698078480",
              "arrivalDelay": "0",
              "departureDelay": "0",
              "departureCanceled": "0",
              "left": "0",
              "isExtraStop": "0",
              "platform": "?",
              "platforminfo": { "name": "?", "normal": "1" }
            }
          ]
        },
        "departureConnection": "http://irail.be/connections/8821196/20231023/IC3017",
        "direction": { "name": "De Panne" },
        "left": "0",
        "walking": "0"
      },
      "arrival": {
        "delay": "0",
        "station": "Ghent-Dampoort",
        "stationinfo": {
          "locationX": "3.740591",
          "locationY": "51.056365",
          "id": "BE.NMBS.008893120",
          "name": "Ghent-Dampoort",
          "@id": "http://irail.be/stations/NMBS/008893120",
          "standardname": "Gent-Dampoort"
        },
        "time": "1698079200",
        "vehicle": "BE.NMBS.IC3017",
        "vehicleinfo": {
          "name": "BE.NMBS.IC3017",
          "shortname": "IC3017",
          "number": "3017",
          "type": "IC",
          "locationX": "0",
          "locationY": "0",
          "@id": "http://irail.be/vehicle/IC3017"
        },
        "platform": "1",
        "platforminfo": { "name": "1", "normal": "1" },
        "canceled": "0",
        "direction": { "name": "De Panne" },
        "arrived": "0",
        "walking": "0"
      },
      "duration": "2340",
      "remarks": { "number": "0", "remark": [] },
      "alerts": { "number": "0", "alert": [] }
    },
    {
      "id": "1",
      "departure": {
        "delay": "60",
        "station": "Antwerp-South",
        "stationinfo": {
          "locationX": "4.390259",
          "locationY": "51.197828",
          "id": "BE.NMBS.008821196",
          "name": "Antwerp-South",
          "@id": "http://irail.be/stations/NMBS/008821196",
          "standardname": "Antwerpen-Zuid"
        },
        "time": "1698077820",
        "vehicle": "BE.NMBS.IC1839",
        "vehicleinfo": {
          "name": "BE.NMBS.IC1839",
          "shortname": "IC1839",
          "number": "1839",
          "type": "IC",
          "locationX": "0",
          "locationY": "0",
          "@id": "http://irail.be/vehicle/IC1839"
        },
        "platform": "3",
        "platforminfo": { "name": "3", "normal": "1" },
        "canceled": "0",
        "stops": {
          "number": "4",
          "stop": [
            {
              "id": "0",
              "station": "Beveren",
              "stationinfo": {
                "locationX": "4.25952",
                "locationY": "51.208336",
                "id": "BE.NMBS.008894748",
                "name": "Beveren",
                "@id": "http://irail.be/stations/NMBS/008894748",
                "standardname": "Beveren"
              },
              "scheduledArrivalTime": "1698078360",
              "arrivalCanceled": "0",
              "arrived": "0",
              "scheduledDepartureTime": "1698078420",
              "arrivalDelay": "0",
              "departureDelay": "0",
              "departureCanceled": "0",
              "left": "0",
              "isExtraStop": "0",
              "platform": "?",
              "platforminfo": { "name": "?", "normal": "1" }
            },
            {
              "id": "1",
              "station": "Sint-Niklaas",
              "stationinfo": {
                "locationX": "4.142966",
                "locationY": "51.171472",
                "id": "BE.NMBS.008894508",
                "name": "Sint-Niklaas",
                "@id": "http://irail.be/stations/NMBS/008894508",
                "standardname": "Sint-Niklaas"
              },
              "scheduledArrivalTime": "1698078840",
              "arrivalCanceled": "0",
              "arrived": "0",
              "scheduledDepartureTime": "1698078960",
              "arrivalDelay": "0",
              "departureDelay": "0",
              "departureCanceled": "0",
              "left": "0",
              "isExtraStop": "0",
              "platform": "?",
              "platforminfo": { "name": "?", "normal": "1" }
            },
            {
              "id": "2",
              "station": "Lokeren",
              "stationinfo": {
                "locationX": "3.987794",
                "locationY": "51.108062",
                "id": "BE.NMBS.008894201",
                "name": "Lokeren",
                "@id": "http://irail.be/stations/NMBS/008894201",
                "standardname": "Lokeren"
              },
              "scheduledArrivalTime": "1698079500",
              "arrivalCanceled": "0",
              "arrived": "0",
              "scheduledDepartureTime": "1698079560",
              "arrivalDelay": "0",
              "departureDelay": "0",
              "departureCanceled": "0",
              "left": "0",
              "isExtraStop": "0",
              "platform": "?",
              "platforminfo": { "name": "?", "normal": "1" }
            },
            {
              "id": "3",
              "station": "Beervelde",
              "stationinfo": {
                "locationX": "3.879384",
                "locationY": "51.08753",
                "id": "BE.NMBS.008894151",
                "name": "Beervelde",
                "@id": "http://irail.be/stations/NMBS/008894151",
                "standardname": "Beervelde"
              },
              "scheduledArrivalTime": "1698079860",
              "arrivalCanceled": "0",
              "arrived": "0",
              "scheduledDepartureTime": "1698079920",
              "arrivalDelay": "0",
              "departureDelay": "0",
              "departureCanceled": "0",
              "left": "0",
              "isExtraStop": "0",
              "platform": "?",
              "platforminfo": { "name": "?", "normal": "1" }
            }
          ]
        },
        "departureConnection": "http://irail.be/connections/8821196/20231023/IC1839",
        "direction": { "name": "Oostende" },
        "left": "0",
        "walking": "0"
      },
      "arrival": {
        "delay": "0",
        "station": "Ghent-Dampoort",
        "stationinfo": {
          "locationX": "3.740591",
          "locationY": "51.056365",
          "id": "BE.NMBS.008893120",
          "name": "Ghent-Dampoort",
          "@id": "http://irail.be/stations/NMBS/008893120",
          "standardname": "Gent-Dampoort"
        },
        "time": "1698080340",
        "vehicle": "BE.NMBS.IC1839",
        "vehicleinfo": {
          "name": "BE.NMBS.IC1839",
          "shortname": "IC1839",
          "number": "1839",
          "type": "IC",
          "locationX": "0",
          "locationY": "0",
          "@id": "http://irail.be/vehicle/IC1839"
        },
        "platform": "1",
        "platforminfo": { "name": "1", "normal": "1" },
        "canceled": "0",
        "direction": { "name": "Oostende" },
        "arrived": "0",
        "walking": "0"
      },
      "duration": "2520",
      "remarks": { "number": "0", "remark": [] },
      "alerts": { "number": "0", "alert": [] }
    },
    {
      "id": "2",
      "departure": {
        "delay": "0",
        "station": "Antwerp-South",
        "stationinfo": {
          "locationX": "4.390259",
          "locationY": "51.197828",
          "id": "BE.NMBS.008821196",
          "name": "Antwerp-South",
          "@id": "http://irail.be/stations/NMBS/008821196",
          "standardname": "Antwerpen-Zuid"
        },
        "time": "1698078660",
        "vehicle": "BE.NMBS.S342688",
        "vehicleinfo": {
          "name": "BE.NMBS.S342688",
          "shortname": "S342688",
          "number": "2688",
          "type": "S34",
          "locationX": "0",
          "locationY": "0",
          "@id": "http://irail.be/vehicle/S342688"
        },
        "platform": "2",
        "platforminfo": { "name": "2", "normal": "1" },
        "canceled": "0",
        "departureConnection": "http://irail.be/connections/8821196/20231023/S342688",
        "direction": { "name": "Antwerpen-Centraal" },
        "left": "0",
        "walking": "0"
      },
      "arrival": {
        "delay": "0",
        "station": "Ghent-Dampoort",
        "stationinfo": {
          "locationX": "3.740591",
          "locationY": "51.056365",
          "id": "BE.NMBS.008893120",
          "name": "Ghent-Dampoort",
          "@id": "http://irail.be/stations/NMBS/008893120",
          "standardname": "Gent-Dampoort"
        },
        "time": "1698081840",
        "vehicle": "BE.NMBS.IC718",
        "vehicleinfo": {
          "name": "BE.NMBS.IC718",
          "shortname": "IC718",
          "number": "718",
          "type": "IC",
          "locationX": "0",
          "locationY": "0",
          "@id": "http://irail.be/vehicle/IC718"
        },
        "platform": "1",
        "platforminfo": { "name": "1", "normal": "1" },
        "canceled": "0",
        "direction": { "name": "Lille Flandres (FR)" },
        "arrived": "0",
        "walking": "0"
      },
      "vias": {
        "number": "1",
        "via": [
          {
            "id": "0",
            "arrival": {
              "time": "1698078900",
              "platform": "7",
              "platforminfo": { "name": "7", "normal": "1" },
              "isExtraStop": "0",
              "canceled": "0",
              "delay": "0",
              "arrived": "0",
              "walking": "0",
              "direction": { "name": "Antwerpen-Centraal" },
              "vehicle": "BE.NMBS.S342688",
              "vehicleinfo": {
                "name": "BE.NMBS.S342688",
                "shortname": "S342688",
                "number": "2688",
                "type": "S34",
                "locationX": "0",
                "locationY": "0",
                "@id": "http://irail.be/vehicle/S342688"
              },
              "departureConnection": "http://irail.be/connections/8821121/20231023/S342688"
            },
            "departure": {
              "time": "1698079380",
              "platform": "6",
              "platforminfo": { "name": "6", "normal": "1" },
              "isExtraStop": "0",
              "canceled": "0",
              "delay": "0",
              "left": "0",
              "walking": "0",
              "direction": { "name": "Lille Flandres (FR)" },
              "vehicle": "BE.NMBS.IC718",
              "vehicleinfo": {
                "name": "BE.NMBS.IC718",
                "shortname": "IC718",
                "number": "718",
                "type": "IC",
                "locationX": "0",
                "locationY": "0",
                "@id": "http://irail.be/vehicle/IC718"
              },
              "stops": {
                "number": "2",
                "stop": [
                  {
                    "id": "0",
                    "station": "Sint-Niklaas",
                    "stationinfo": {
                      "locationX": "4.142966",
                      "locationY": "51.171472",
                      "id": "BE.NMBS.008894508",
                      "name": "Sint-Niklaas",
                      "@id": "http://irail.be/stations/NMBS/008894508",
                      "standardname": "Sint-Niklaas"
                    },
                    "scheduledArrivalTime": "1698080400",
                    "arrivalCanceled": "0",
                    "arrived": "0",
                    "scheduledDepartureTime": "1698080520",
                    "arrivalDelay": "0",
                    "departureDelay": "0",
                    "departureCanceled": "0",
                    "left": "0",
                    "isExtraStop": "0",
                    "platform": "?",
                    "platforminfo": { "name": "?", "normal": "1" }
                  },
                  {
                    "id": "1",
                    "station": "Lokeren",
                    "stationinfo": {
                      "locationX": "3.987794",
                      "locationY": "51.108062",
                      "id": "BE.NMBS.008894201",
                      "name": "Lokeren",
                      "@id": "http://irail.be/stations/NMBS/008894201",
                      "standardname": "Lokeren"
                    },
                    "scheduledArrivalTime": "1698081060",
                    "arrivalCanceled": "0",
                    "arrived": "0",
                    "scheduledDepartureTime": "1698081120",
                    "arrivalDelay": "0",
                    "departureDelay": "0",
                    "departureCanceled": "0",
                    "left": "0",
                    "isExtraStop": "0",
                    "platform": "?",
                    "platforminfo": { "name": "?", "normal": "1" }
                  }
                ]
              },
              "departureConnection": "http://irail.be/connections/8821121/20231023/IC718"
            },
            "timeBetween": "480",
            "station": "Antwerp-Berchem",
            "stationinfo": {
              "locationX": "4.432221",
              "locationY": "51.19923",
              "id": "BE.NMBS.008821121",
              "name": "Antwerp-Berchem",
              "@id": "http://irail.be/stations/NMBS/008821121",
              "standardname": "Antwerpen-Berchem"
            },
            "vehicle": "BE.NMBS.S342688",
            "vehicleinfo": {
              "name": "BE.NMBS.S342688",
              "shortname": "S342688",
              "number": "2688",
              "type": "S34",
              "locationX": "0",
              "locationY": "0",
              "@id": "http://irail.be/vehicle/S342688"
            },
            "direction": { "name": "Antwerpen-Centraal" }
          }
        ]
      },
      "duration": "3180",
      "remarks": { "number": "0", "remark": [] },
      "alerts": { "number": "0", "alert": [] }
    },
    {
      "id": "3",
      "departure": {
        "delay": "60",
        "station": "Antwerp-South",
        "stationinfo": {
          "locationX": "4.390259",
          "locationY": "51.197828",
          "id": "BE.NMBS.008821196",
          "name": "Antwerp-South",
          "@id": "http://irail.be/stations/NMBS/008821196",
          "standardname": "Antwerpen-Zuid"
        },
        "time": "1698080460",
        "vehicle": "BE.NMBS.IC3018",
        "vehicleinfo": {
          "name": "BE.NMBS.IC3018",
          "shortname": "IC3018",
          "number": "3018",
          "type": "IC",
          "locationX": "0",
          "locationY": "0",
          "@id": "http://irail.be/vehicle/IC3018"
        },
        "platform": "3",
        "platforminfo": { "name": "3", "normal": "1" },
        "canceled": "0",
        "stops": {
          "number": "2",
          "stop": [
            {
              "id": "0",
              "station": "Sint-Niklaas",
              "stationinfo": {
                "locationX": "4.142966",
                "locationY": "51.171472",
                "id": "BE.NMBS.008894508",
                "name": "Sint-Niklaas",
                "@id": "http://irail.be/stations/NMBS/008894508",
                "standardname": "Sint-Niklaas"
              },
              "scheduledArrivalTime": "1698081300",
              "arrivalCanceled": "0",
              "arrived": "0",
              "scheduledDepartureTime": "1698081420",
              "arrivalDelay": "0",
              "departureDelay": "0",
              "departureCanceled": "0",
              "left": "0",
              "isExtraStop": "0",
              "platform": "?",
              "platforminfo": { "name": "?", "normal": "1" }
            },
            {
              "id": "1",
              "station": "Lokeren",
              "stationinfo": {
                "locationX": "3.987794",
                "locationY": "51.108062",
                "id": "BE.NMBS.008894201",
                "name": "Lokeren",
                "@id": "http://irail.be/stations/NMBS/008894201",
                "standardname": "Lokeren"
              },
              "scheduledArrivalTime": "1698081960",
              "arrivalCanceled": "0",
              "arrived": "0",
              "scheduledDepartureTime": "1698082080",
              "arrivalDelay": "0",
              "departureDelay": "0",
              "departureCanceled": "0",
              "left": "0",
              "isExtraStop": "0",
              "platform": "?",
              "platforminfo": { "name": "?", "normal": "1" }
            }
          ]
        },
        "departureConnection": "http://irail.be/connections/8821196/20231023/IC3018",
        "direction": { "name": "De Panne" },
        "left": "0",
        "walking": "0"
      },
      "arrival": {
        "delay": "0",
        "station": "Ghent-Dampoort",
        "stationinfo": {
          "locationX": "3.740591",
          "locationY": "51.056365",
          "id": "BE.NMBS.008893120",
          "name": "Ghent-Dampoort",
          "@id": "http://irail.be/stations/NMBS/008893120",
          "standardname": "Gent-Dampoort"
        },
        "time": "1698082800",
        "vehicle": "BE.NMBS.IC3018",
        "vehicleinfo": {
          "name": "BE.NMBS.IC3018",
          "shortname": "IC3018",
          "number": "3018",
          "type": "IC",
          "locationX": "0",
          "locationY": "0",
          "@id": "http://irail.be/vehicle/IC3018"
        },
        "platform": "1",
        "platforminfo": { "name": "1", "normal": "1" },
        "canceled": "0",
        "direction": { "name": "De Panne" },
        "arrived": "0",
        "walking": "0"
      },
      "duration": "2340",
      "remarks": { "number": "0", "remark": [] },
      "alerts": { "number": "0", "alert": [] }
    },
    {
      "id": "4",
      "departure": {
        "delay": "60",
        "station": "Antwerp-South",
        "stationinfo": {
          "locationX": "4.390259",
          "locationY": "51.197828",
          "id": "BE.NMBS.008821196",
          "name": "Antwerp-South",
          "@id": "http://irail.be/stations/NMBS/008821196",
          "standardname": "Antwerpen-Zuid"
        },
        "time": "1698081420",
        "vehicle": "BE.NMBS.IC1840",
        "vehicleinfo": {
          "name": "BE.NMBS.IC1840",
          "shortname": "IC1840",
          "number": "1840",
          "type": "IC",
          "locationX": "0",
          "locationY": "0",
          "@id": "http://irail.be/vehicle/IC1840"
        },
        "platform": "3",
        "platforminfo": { "name": "3", "normal": "1" },
        "canceled": "0",
        "stops": {
          "number": "4",
          "stop": [
            {
              "id": "0",
              "station": "Beveren",
              "stationinfo": {
                "locationX": "4.25952",
                "locationY": "51.208336",
                "id": "BE.NMBS.008894748",
                "name": "Beveren",
                "@id": "http://irail.be/stations/NMBS/008894748",
                "standardname": "Beveren"
              },
              "scheduledArrivalTime": "1698081960",
              "arrivalCanceled": "0",
              "arrived": "0",
              "scheduledDepartureTime": "1698082020",
              "arrivalDelay": "0",
              "departureDelay": "0",
              "departureCanceled": "0",
              "left": "0",
              "isExtraStop": "0",
              "platform": "?",
              "platforminfo": { "name": "?", "normal": "1" }
            },
            {
              "id": "1",
              "station": "Sint-Niklaas",
              "stationinfo": {
                "locationX": "4.142966",
                "locationY": "51.171472",
                "id": "BE.NMBS.008894508",
                "name": "Sint-Niklaas",
                "@id": "http://irail.be/stations/NMBS/008894508",
                "standardname": "Sint-Niklaas"
              },
              "scheduledArrivalTime": "1698082440",
              "arrivalCanceled": "0",
              "arrived": "0",
              "scheduledDepartureTime": "1698082560",
              "arrivalDelay": "0",
              "departureDelay": "0",
              "departureCanceled": "0",
              "left": "0",
              "isExtraStop": "0",
              "platform": "?",
              "platforminfo": { "name": "?", "normal": "1" }
            },
            {
              "id": "2",
              "station": "Lokeren",
              "stationinfo": {
                "locationX": "3.987794",
                "locationY": "51.108062",
                "id": "BE.NMBS.008894201",
                "name": "Lokeren",
                "@id": "http://irail.be/stations/NMBS/008894201",
                "standardname": "Lokeren"
              },
              "scheduledArrivalTime": "1698083100",
              "arrivalCanceled": "0",
              "arrived": "0",
              "scheduledDepartureTime": "1698083160",
              "arrivalDelay": "0",
              "departureDelay": "0",
              "departureCanceled": "0",
              "left": "0",
              "isExtraStop": "0",
              "platform": "?",
              "platforminfo": { "name": "?", "normal": "1" }
            },
            {
              "id": "3",
              "station": "Beervelde",
              "stationinfo": {
                "locationX": "3.879384",
                "locationY": "51.08753",
                "id": "BE.NMBS.008894151",
                "name": "Beervelde",
                "@id": "http://irail.be/stations/NMBS/008894151",
                "standardname": "Beervelde"
              },
              "scheduledArrivalTime": "1698083460",
              "arrivalCanceled": "0",
              "arrived": "0",
              "scheduledDepartureTime": "1698083520",
              "arrivalDelay": "0",
              "departureDelay": "0",
              "departureCanceled": "0",
              "left": "0",
              "isExtraStop": "0",
              "platform": "?",
              "platforminfo": { "name": "?", "normal": "1" }
            }
          ]
        },
        "departureConnection": "http://irail.be/connections/8821196/20231023/IC1840",
        "direction": { "name": "Oostende" },
        "left": "0",
        "walking": "0"
      },
      "arrival": {
        "delay": "0",
        "station": "Ghent-Dampoort",
        "stationinfo": {
          "locationX": "3.740591",
          "locationY": "51.056365",
          "id": "BE.NMBS.008893120",
          "name": "Ghent-Dampoort",
          "@id": "http://irail.be/stations/NMBS/008893120",
          "standardname": "Gent-Dampoort"
        },
        "time": "1698083940",
        "vehicle": "BE.NMBS.IC1840",
        "vehicleinfo": {
          "name": "BE.NMBS.IC1840",
          "shortname": "IC1840",
          "number": "1840",
          "type": "IC",
          "locationX": "0",
          "locationY": "0",
          "@id": "http://irail.be/vehicle/IC1840"
        },
        "platform": "1",
        "platforminfo": { "name": "1", "normal": "1" },
        "canceled": "0",
        "direction": { "name": "Oostende" },
        "arrived": "0",
        "walking": "0"
      },
      "duration": "2520",
      "remarks": { "number": "0", "remark": [] },
      "alerts": { "number": "0", "alert": [] }
    },
    {
      "id": "5",
      "departure": {
        "delay": "0",
        "station": "Antwerp-South",
        "stationinfo": {
          "locationX": "4.390259",
          "locationY": "51.197828",
          "id": "BE.NMBS.008821196",
          "name": "Antwerp-South",
          "@id": "http://irail.be/stations/NMBS/008821196",
          "standardname": "Antwerpen-Zuid"
        },
        "time": "1698082260",
        "vehicle": "BE.NMBS.S342689",
        "vehicleinfo": {
          "name": "BE.NMBS.S342689",
          "shortname": "S342689",
          "number": "2689",
          "type": "S34",
          "locationX": "0",
          "locationY": "0",
          "@id": "http://irail.be/vehicle/S342689"
        },
        "platform": "2",
        "platforminfo": { "name": "2", "normal": "1" },
        "canceled": "1",
        "departureConnection": "http://irail.be/connections/8821196/20231023/S342689",
        "direction": { "name": "Antwerpen-Centraal" },
        "left": "0",
        "walking": "0"
      },
      "arrival": {
        "delay": "0",
        "station": "Ghent-Dampoort",
        "stationinfo": {
          "locationX": "3.740591",
          "locationY": "51.056365",
          "id": "BE.NMBS.008893120",
          "name": "Ghent-Dampoort",
          "@id": "http://irail.be/stations/NMBS/008893120",
          "standardname": "Gent-Dampoort"
        },
        "time": "1698085440",
        "vehicle": "BE.NMBS.IC719",
        "vehicleinfo": {
          "name": "BE.NMBS.IC719",
          "shortname": "IC719",
          "number": "719",
          "type": "IC",
          "locationX": "0",
          "locationY": "0",
          "@id": "http://irail.be/vehicle/IC719"
        },
        "platform": "1",
        "platforminfo": { "name": "1", "normal": "1" },
        "canceled": "0",
        "direction": { "name": "Lille Flandres (FR)" },
        "arrived": "0",
        "walking": "0"
      },
      "vias": {
        "number": "1",
        "via": [
          {
            "id": "0",
            "arrival": {
              "time": "1698082500",
              "platform": "7",
              "platforminfo": { "name": "7", "normal": "1" },
              "isExtraStop": "0",
              "canceled": "0",
              "delay": "0",
              "arrived": "0",
              "walking": "0",
              "direction": { "name": "Antwerpen-Centraal" },
              "vehicle": "BE.NMBS.S342689",
              "vehicleinfo": {
                "name": "BE.NMBS.S342689",
                "shortname": "S342689",
                "number": "2689",
                "type": "S34",
                "locationX": "0",
                "locationY": "0",
                "@id": "http://irail.be/vehicle/S342689"
              },
              "departureConnection": "http://irail.be/connections/8821121/20231023/S342689"
            },
            "departure": {
              "time": "1698082980",
              "platform": "6",
              "platforminfo": { "name": "6", "normal": "1" },
              "isExtraStop": "0",
              "canceled": "1",
              "delay": "0",
              "left": "0",
              "walking": "0",
              "direction": { "name": "Lille Flandres (FR)" },
              "vehicle": "BE.NMBS.IC719",
              "vehicleinfo": {
                "name": "BE.NMBS.IC719",
                "shortname": "IC719",
                "number": "719",
                "type": "IC",
                "locationX": "0",
                "locationY": "0",
                "@id": "http://irail.be/vehicle/IC719"
              },
              "stops": {
                "number": "2",
                "stop": [
                  {
                    "id": "0",
                    "station": "Sint-Niklaas",
                    "stationinfo": {
                      "locationX": "4.142966",
                      "locationY": "51.171472",
                      "id": "BE.NMBS.008894508",
                      "name": "Sint-Niklaas",
                      "@id": "http://irail.be/stations/NMBS/008894508",
                      "standardname": "Sint-Niklaas"
                    },
                    "scheduledArrivalTime": "1698084000",
                    "arrivalCanceled": "0",
                    "arrived": "0",
                    "scheduledDepartureTime": "1698084120",
                    "arrivalDelay": "0",
                    "departureDelay": "0",
                    "departureCanceled": "0",
                    "left": "0",
                    "isExtraStop": "0",
                    "platform": "?",
                    "platforminfo": { "name": "?", "normal": "1" }
                  },
                  {
                    "id": "1",
                    "station": "Lokeren",
                    "stationinfo": {
                      "locationX": "3.987794",
                      "locationY": "51.108062",
                      "id": "BE.NMBS.008894201",
                      "name": "Lokeren",
                      "@id": "http://irail.be/stations/NMBS/008894201",
                      "standardname": "Lokeren"
                    },
                    "scheduledArrivalTime": "1698084660",
                    "arrivalCanceled": "0",
                    "arrived": "0",
                    "scheduledDepartureTime": "1698084720",
                    "arrivalDelay": "0",
                    "departureDelay": "0",
                    "departureCanceled": "0",
                    "left": "0",
                    "isExtraStop": "0",
                    "platform": "?",
                    "platforminfo": { "name": "?", "normal": "1" }
                  }
                ]
              },
              "departureConnection": "http://irail.be/connections/8821121/20231023/IC719"
            },
            "timeBetween": "480",
            "station": "Antwerp-Berchem",
            "stationinfo": {
              "locationX": "4.432221",
              "locationY": "51.19923",
              "id": "BE.NMBS.008821121",
              "name": "Antwerp-Berchem",
              "@id": "http://irail.be/stations/NMBS/008821121",
              "standardname": "Antwerpen-Berchem"
            },
            "vehicle": "BE.NMBS.S342689",
            "vehicleinfo": {
              "name": "BE.NMBS.S342689",
              "shortname": "S342689",
              "number": "2689",
              "type": "S34",
              "locationX": "0",
              "locationY": "0",
              "@id": "http://irail.be/vehicle/S342689"
            },
            "direction": { "name": "Antwerpen-Centraal" }
          }
        ]
      },
      "duration": "3180",
      "remarks": { "number": "0", "remark": [] },
      "alerts": { "number": "0", "alert": [] }
    }
  ]
}

"#;
